services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    environment:
      MSSQL_SA_PASSWORD: "Str0ngP@ssword!"
      ACCEPT_EULA: "Yes"
      MSSQL_PID: "Developer"
      MSSQL_ENCRYPT: "DISABLED"
    ports:
      - "1433:1433"

  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: authservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - SQLSERVER_HOST=sqlserver
      - SQLSERVER_PORT=1433
      - SQLSERVER_USER=sa
      - SQLSERVER_PASSWORD=Str0ngP@ssword!
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver

  inventoryservice:
    build:
      context: ./InventoryService
      dockerfile: Dockerfile
    container_name: inventoryservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQLSERVER_HOST=sqlserver
      - SQLSERVER_PORT=1433
      - SQLSERVER_USER=sa
      - SQLSERVER_PASSWORD=Str0ngP@ssword!
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver

  salesservice:
    build:
      context: ./SalesService
      dockerfile: Dockerfile
    container_name: salesservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQLSERVER_HOST=sqlserver
      - SQLSERVER_PORT=1433
      - SQLSERVER_USER=sa
      - SQLSERVER_PASSWORD=Str0ngP@ssword!
      - AUTH_URL=http://authservice:8080
      - INVENTORY_URL=http://inventoryservice:8080
    ports:
      - "5002:8080"
    depends_on:
      - sqlserver
      - authservice
      - inventoryservice
networks:
  default:
    driver: bridge
